from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from energy_manager_service.models.base_model import Model
from energy_manager_service.models.scheduling import Scheduling
from energy_manager_service import util

from energy_manager_service.models.scheduling import Scheduling  # noqa: E501

class AvailableFlexibilityResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id=None, baseline=None, flexibility_downward=None, flexibility_upward=None):  # noqa: E501
        """AvailableFlexibilityResponse - a model defined in OpenAPI

        :param user_id: The user_id of this AvailableFlexibilityResponse.  # noqa: E501
        :type user_id: str
        :param baseline: The baseline of this AvailableFlexibilityResponse.  # noqa: E501
        :type baseline: List[Scheduling]
        :param flexibility_downward: The flexibility_downward of this AvailableFlexibilityResponse.  # noqa: E501
        :type flexibility_downward: List[Scheduling]
        :param flexibility_upward: The flexibility_upward of this AvailableFlexibilityResponse.  # noqa: E501
        :type flexibility_upward: List[Scheduling]
        """
        self.openapi_types = {
            'user_id': str,
            'baseline': List[Scheduling],
            'flexibility_downward': List[Scheduling],
            'flexibility_upward': List[Scheduling]
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'baseline': 'baseline',
            'flexibility_downward': 'flexibility_downward',
            'flexibility_upward': 'flexibility_upward'
        }

        self._user_id = user_id
        self._baseline = baseline
        self._flexibility_downward = flexibility_downward
        self._flexibility_upward = flexibility_upward

    @classmethod
    def from_dict(cls, dikt) -> 'AvailableFlexibilityResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AvailableFlexibilityResponse of this AvailableFlexibilityResponse.  # noqa: E501
        :rtype: AvailableFlexibilityResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this AvailableFlexibilityResponse.


        :return: The user_id of this AvailableFlexibilityResponse.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this AvailableFlexibilityResponse.


        :param user_id: The user_id of this AvailableFlexibilityResponse.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501
        if user_id is not None and len(user_id) > 10:
            raise ValueError("Invalid value for `user_id`, length must be less than or equal to `10`")  # noqa: E501
        if user_id is not None and len(user_id) < 10:
            raise ValueError("Invalid value for `user_id`, length must be greater than or equal to `10`")  # noqa: E501

        self._user_id = user_id

    @property
    def baseline(self) -> List[Scheduling]:
        """Gets the baseline of this AvailableFlexibilityResponse.


        :return: The baseline of this AvailableFlexibilityResponse.
        :rtype: List[Scheduling]
        """
        return self._baseline

    @baseline.setter
    def baseline(self, baseline: List[Scheduling]):
        """Sets the baseline of this AvailableFlexibilityResponse.


        :param baseline: The baseline of this AvailableFlexibilityResponse.
        :type baseline: List[Scheduling]
        """
        if baseline is None:
            raise ValueError("Invalid value for `baseline`, must not be `None`")  # noqa: E501

        self._baseline = baseline

    @property
    def flexibility_downward(self) -> List[Scheduling]:
        """Gets the flexibility_downward of this AvailableFlexibilityResponse.


        :return: The flexibility_downward of this AvailableFlexibilityResponse.
        :rtype: List[Scheduling]
        """
        return self._flexibility_downward

    @flexibility_downward.setter
    def flexibility_downward(self, flexibility_downward: List[Scheduling]):
        """Sets the flexibility_downward of this AvailableFlexibilityResponse.


        :param flexibility_downward: The flexibility_downward of this AvailableFlexibilityResponse.
        :type flexibility_downward: List[Scheduling]
        """

        self._flexibility_downward = flexibility_downward

    @property
    def flexibility_upward(self) -> List[Scheduling]:
        """Gets the flexibility_upward of this AvailableFlexibilityResponse.


        :return: The flexibility_upward of this AvailableFlexibilityResponse.
        :rtype: List[Scheduling]
        """
        return self._flexibility_upward

    @flexibility_upward.setter
    def flexibility_upward(self, flexibility_upward: List[Scheduling]):
        """Sets the flexibility_upward of this AvailableFlexibilityResponse.


        :param flexibility_upward: The flexibility_upward of this AvailableFlexibilityResponse.
        :type flexibility_upward: List[Scheduling]
        """

        self._flexibility_upward = flexibility_upward
