from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from energy_manager_service.models.base_model import Model
from energy_manager_service import util


class DelayStatusBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, delay_call_ok=None, delay_call_description=None):  # noqa: E501
        """DelayStatusBody - a model defined in OpenAPI

        :param delay_call_ok: The delay_call_ok of this DelayStatusBody.  # noqa: E501
        :type delay_call_ok: bool
        :param delay_call_description: The delay_call_description of this DelayStatusBody.  # noqa: E501
        :type delay_call_description: str
        """
        self.openapi_types = {
            'delay_call_ok': bool,
            'delay_call_description': str
        }

        self.attribute_map = {
            'delay_call_ok': 'delay_call_ok',
            'delay_call_description': 'delay_call_description'
        }

        self._delay_call_ok = delay_call_ok
        self._delay_call_description = delay_call_description

    @classmethod
    def from_dict(cls, dikt) -> 'DelayStatusBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DelayStatusBody of this DelayStatusBody.  # noqa: E501
        :rtype: DelayStatusBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def delay_call_ok(self) -> bool:
        """Gets the delay_call_ok of this DelayStatusBody.


        :return: The delay_call_ok of this DelayStatusBody.
        :rtype: bool
        """
        return self._delay_call_ok

    @delay_call_ok.setter
    def delay_call_ok(self, delay_call_ok: bool):
        """Sets the delay_call_ok of this DelayStatusBody.


        :param delay_call_ok: The delay_call_ok of this DelayStatusBody.
        :type delay_call_ok: bool
        """
        if delay_call_ok is None:
            raise ValueError("Invalid value for `delay_call_ok`, must not be `None`")  # noqa: E501

        self._delay_call_ok = delay_call_ok

    @property
    def delay_call_description(self) -> str:
        """Gets the delay_call_description of this DelayStatusBody.


        :return: The delay_call_description of this DelayStatusBody.
        :rtype: str
        """
        return self._delay_call_description

    @delay_call_description.setter
    def delay_call_description(self, delay_call_description: str):
        """Sets the delay_call_description of this DelayStatusBody.


        :param delay_call_description: The delay_call_description of this DelayStatusBody.
        :type delay_call_description: str
        """

        self._delay_call_description = delay_call_description
