from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from energy_manager_service.models.base_model import Model
from energy_manager_service.models.flex_accept_body_setpoints_inner import FlexAcceptBodySetpointsInner
from energy_manager_service import util

from energy_manager_service.models.flex_accept_body_setpoints_inner import FlexAcceptBodySetpointsInner  # noqa: E501

class FlexAcceptBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data_point=None, creation_timestamp=None, setpoints=None):  # noqa: E501
        """FlexAcceptBody - a model defined in OpenAPI

        :param data_point: The data_point of this FlexAcceptBody.  # noqa: E501
        :type data_point: str
        :param creation_timestamp: The creation_timestamp of this FlexAcceptBody.  # noqa: E501
        :type creation_timestamp: datetime
        :param setpoints: The setpoints of this FlexAcceptBody.  # noqa: E501
        :type setpoints: List[FlexAcceptBodySetpointsInner]
        """
        self.openapi_types = {
            'data_point': str,
            'creation_timestamp': datetime,
            'setpoints': List[FlexAcceptBodySetpointsInner]
        }

        self.attribute_map = {
            'data_point': 'data_point',
            'creation_timestamp': 'creation_timestamp',
            'setpoints': 'setpoints'
        }

        self._data_point = data_point
        self._creation_timestamp = creation_timestamp
        self._setpoints = setpoints

    @classmethod
    def from_dict(cls, dikt) -> 'FlexAcceptBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FlexAcceptBody of this FlexAcceptBody.  # noqa: E501
        :rtype: FlexAcceptBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data_point(self) -> str:
        """Gets the data_point of this FlexAcceptBody.


        :return: The data_point of this FlexAcceptBody.
        :rtype: str
        """
        return self._data_point

    @data_point.setter
    def data_point(self, data_point: str):
        """Sets the data_point of this FlexAcceptBody.


        :param data_point: The data_point of this FlexAcceptBody.
        :type data_point: str
        """

        self._data_point = data_point

    @property
    def creation_timestamp(self) -> datetime:
        """Gets the creation_timestamp of this FlexAcceptBody.


        :return: The creation_timestamp of this FlexAcceptBody.
        :rtype: datetime
        """
        return self._creation_timestamp

    @creation_timestamp.setter
    def creation_timestamp(self, creation_timestamp: datetime):
        """Sets the creation_timestamp of this FlexAcceptBody.


        :param creation_timestamp: The creation_timestamp of this FlexAcceptBody.
        :type creation_timestamp: datetime
        """

        self._creation_timestamp = creation_timestamp

    @property
    def setpoints(self) -> List[FlexAcceptBodySetpointsInner]:
        """Gets the setpoints of this FlexAcceptBody.


        :return: The setpoints of this FlexAcceptBody.
        :rtype: List[FlexAcceptBodySetpointsInner]
        """
        return self._setpoints

    @setpoints.setter
    def setpoints(self, setpoints: List[FlexAcceptBodySetpointsInner]):
        """Sets the setpoints of this FlexAcceptBody.


        :param setpoints: The setpoints of this FlexAcceptBody.
        :type setpoints: List[FlexAcceptBodySetpointsInner]
        """
        if setpoints is not None and len(setpoints) > 96:
            raise ValueError("Invalid value for `setpoints`, number of items must be less than or equal to `96`")  # noqa: E501
        if setpoints is not None and len(setpoints) < 24:
            raise ValueError("Invalid value for `setpoints`, number of items must be greater than or equal to `24`")  # noqa: E501

        self._setpoints = setpoints
