from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from energy_manager_service.models.base_model import Model
from energy_manager_service import util


class FlexAcceptBodySetpointsInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, time_interval_start=None, time_interval_end=None, power_value=None):  # noqa: E501
        """FlexAcceptBodySetpointsInner - a model defined in OpenAPI

        :param time_interval_start: The time_interval_start of this FlexAcceptBodySetpointsInner.  # noqa: E501
        :type time_interval_start: datetime
        :param time_interval_end: The time_interval_end of this FlexAcceptBodySetpointsInner.  # noqa: E501
        :type time_interval_end: datetime
        :param power_value: The power_value of this FlexAcceptBodySetpointsInner.  # noqa: E501
        :type power_value: float
        """
        self.openapi_types = {
            'time_interval_start': datetime,
            'time_interval_end': datetime,
            'power_value': float
        }

        self.attribute_map = {
            'time_interval_start': 'time_interval_start',
            'time_interval_end': 'time_interval_end',
            'power_value': 'power_value'
        }

        self._time_interval_start = time_interval_start
        self._time_interval_end = time_interval_end
        self._power_value = power_value

    @classmethod
    def from_dict(cls, dikt) -> 'FlexAcceptBodySetpointsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FlexAcceptBody_setpoints_inner of this FlexAcceptBodySetpointsInner.  # noqa: E501
        :rtype: FlexAcceptBodySetpointsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time_interval_start(self) -> datetime:
        """Gets the time_interval_start of this FlexAcceptBodySetpointsInner.


        :return: The time_interval_start of this FlexAcceptBodySetpointsInner.
        :rtype: datetime
        """
        return self._time_interval_start

    @time_interval_start.setter
    def time_interval_start(self, time_interval_start: datetime):
        """Sets the time_interval_start of this FlexAcceptBodySetpointsInner.


        :param time_interval_start: The time_interval_start of this FlexAcceptBodySetpointsInner.
        :type time_interval_start: datetime
        """
        if time_interval_start is None:
            raise ValueError("Invalid value for `time_interval_start`, must not be `None`")  # noqa: E501

        self._time_interval_start = time_interval_start

    @property
    def time_interval_end(self) -> datetime:
        """Gets the time_interval_end of this FlexAcceptBodySetpointsInner.


        :return: The time_interval_end of this FlexAcceptBodySetpointsInner.
        :rtype: datetime
        """
        return self._time_interval_end

    @time_interval_end.setter
    def time_interval_end(self, time_interval_end: datetime):
        """Sets the time_interval_end of this FlexAcceptBodySetpointsInner.


        :param time_interval_end: The time_interval_end of this FlexAcceptBodySetpointsInner.
        :type time_interval_end: datetime
        """
        if time_interval_end is None:
            raise ValueError("Invalid value for `time_interval_end`, must not be `None`")  # noqa: E501

        self._time_interval_end = time_interval_end

    @property
    def power_value(self) -> float:
        """Gets the power_value of this FlexAcceptBodySetpointsInner.


        :return: The power_value of this FlexAcceptBodySetpointsInner.
        :rtype: float
        """
        return self._power_value

    @power_value.setter
    def power_value(self, power_value: float):
        """Sets the power_value of this FlexAcceptBodySetpointsInner.


        :param power_value: The power_value of this FlexAcceptBodySetpointsInner.
        :type power_value: float
        """
        if power_value is None:
            raise ValueError("Invalid value for `power_value`, must not be `None`")  # noqa: E501
        if power_value is not None and power_value < 0:  # noqa: E501
            raise ValueError("Invalid value for `power_value`, must be a value greater than or equal to `0`")  # noqa: E501

        self._power_value = power_value
