from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from energy_manager_service.models.base_model import Model
from energy_manager_service import util


class FlexAcceptedAcknowledged(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, accepted=None):  # noqa: E501
        """FlexAcceptedAcknowledged - a model defined in OpenAPI

        :param accepted: The accepted of this FlexAcceptedAcknowledged.  # noqa: E501
        :type accepted: str
        """
        self.openapi_types = {
            'accepted': str
        }

        self.attribute_map = {
            'accepted': 'accepted'
        }

        self._accepted = accepted

    @classmethod
    def from_dict(cls, dikt) -> 'FlexAcceptedAcknowledged':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FlexAcceptedAcknowledged of this FlexAcceptedAcknowledged.  # noqa: E501
        :rtype: FlexAcceptedAcknowledged
        """
        return util.deserialize_model(dikt, cls)

    @property
    def accepted(self) -> str:
        """Gets the accepted of this FlexAcceptedAcknowledged.


        :return: The accepted of this FlexAcceptedAcknowledged.
        :rtype: str
        """
        return self._accepted

    @accepted.setter
    def accepted(self, accepted: str):
        """Sets the accepted of this FlexAcceptedAcknowledged.


        :param accepted: The accepted of this FlexAcceptedAcknowledged.
        :type accepted: str
        """

        self._accepted = accepted
