from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from energy_manager_service.models.base_model import Model
from energy_manager_service import util


class OptimizedCycle(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, serial_number=None, sequence_id=None, scheduled_start_time=None, scheduled_end_time=None, program=None, optimized_start_time=None, acceptance_request=None):  # noqa: E501
        """OptimizedCycle - a model defined in OpenAPI

        :param serial_number: The serial_number of this OptimizedCycle.  # noqa: E501
        :type serial_number: str
        :param sequence_id: The sequence_id of this OptimizedCycle.  # noqa: E501
        :type sequence_id: str
        :param scheduled_start_time: The scheduled_start_time of this OptimizedCycle.  # noqa: E501
        :type scheduled_start_time: datetime
        :param scheduled_end_time: The scheduled_end_time of this OptimizedCycle.  # noqa: E501
        :type scheduled_end_time: datetime
        :param program: The program of this OptimizedCycle.  # noqa: E501
        :type program: str
        :param optimized_start_time: The optimized_start_time of this OptimizedCycle.  # noqa: E501
        :type optimized_start_time: datetime
        :param acceptance_request: The acceptance_request of this OptimizedCycle.  # noqa: E501
        :type acceptance_request: bool
        """
        self.openapi_types = {
            'serial_number': str,
            'sequence_id': str,
            'scheduled_start_time': datetime,
            'scheduled_end_time': datetime,
            'program': str,
            'optimized_start_time': datetime,
            'acceptance_request': bool
        }

        self.attribute_map = {
            'serial_number': 'serial_number',
            'sequence_id': 'sequence_id',
            'scheduled_start_time': 'scheduled_start_time',
            'scheduled_end_time': 'scheduled_end_time',
            'program': 'program',
            'optimized_start_time': 'optimized_start_time',
            'acceptance_request': 'acceptance_request'
        }

        self._serial_number = serial_number
        self._sequence_id = sequence_id
        self._scheduled_start_time = scheduled_start_time
        self._scheduled_end_time = scheduled_end_time
        self._program = program
        self._optimized_start_time = optimized_start_time
        self._acceptance_request = acceptance_request

    @classmethod
    def from_dict(cls, dikt) -> 'OptimizedCycle':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OptimizedCycle of this OptimizedCycle.  # noqa: E501
        :rtype: OptimizedCycle
        """
        return util.deserialize_model(dikt, cls)

    @property
    def serial_number(self) -> str:
        """Gets the serial_number of this OptimizedCycle.


        :return: The serial_number of this OptimizedCycle.
        :rtype: str
        """
        return self._serial_number

    @serial_number.setter
    def serial_number(self, serial_number: str):
        """Sets the serial_number of this OptimizedCycle.


        :param serial_number: The serial_number of this OptimizedCycle.
        :type serial_number: str
        """

        self._serial_number = serial_number

    @property
    def sequence_id(self) -> str:
        """Gets the sequence_id of this OptimizedCycle.


        :return: The sequence_id of this OptimizedCycle.
        :rtype: str
        """
        return self._sequence_id

    @sequence_id.setter
    def sequence_id(self, sequence_id: str):
        """Sets the sequence_id of this OptimizedCycle.


        :param sequence_id: The sequence_id of this OptimizedCycle.
        :type sequence_id: str
        """

        self._sequence_id = sequence_id

    @property
    def scheduled_start_time(self) -> datetime:
        """Gets the scheduled_start_time of this OptimizedCycle.


        :return: The scheduled_start_time of this OptimizedCycle.
        :rtype: datetime
        """
        return self._scheduled_start_time

    @scheduled_start_time.setter
    def scheduled_start_time(self, scheduled_start_time: datetime):
        """Sets the scheduled_start_time of this OptimizedCycle.


        :param scheduled_start_time: The scheduled_start_time of this OptimizedCycle.
        :type scheduled_start_time: datetime
        """

        self._scheduled_start_time = scheduled_start_time

    @property
    def scheduled_end_time(self) -> datetime:
        """Gets the scheduled_end_time of this OptimizedCycle.


        :return: The scheduled_end_time of this OptimizedCycle.
        :rtype: datetime
        """
        return self._scheduled_end_time

    @scheduled_end_time.setter
    def scheduled_end_time(self, scheduled_end_time: datetime):
        """Sets the scheduled_end_time of this OptimizedCycle.


        :param scheduled_end_time: The scheduled_end_time of this OptimizedCycle.
        :type scheduled_end_time: datetime
        """

        self._scheduled_end_time = scheduled_end_time

    @property
    def program(self) -> str:
        """Gets the program of this OptimizedCycle.


        :return: The program of this OptimizedCycle.
        :rtype: str
        """
        return self._program

    @program.setter
    def program(self, program: str):
        """Sets the program of this OptimizedCycle.


        :param program: The program of this OptimizedCycle.
        :type program: str
        """

        self._program = program

    @property
    def optimized_start_time(self) -> datetime:
        """Gets the optimized_start_time of this OptimizedCycle.


        :return: The optimized_start_time of this OptimizedCycle.
        :rtype: datetime
        """
        return self._optimized_start_time

    @optimized_start_time.setter
    def optimized_start_time(self, optimized_start_time: datetime):
        """Sets the optimized_start_time of this OptimizedCycle.


        :param optimized_start_time: The optimized_start_time of this OptimizedCycle.
        :type optimized_start_time: datetime
        """

        self._optimized_start_time = optimized_start_time

    @property
    def acceptance_request(self) -> bool:
        """Gets the acceptance_request of this OptimizedCycle.


        :return: The acceptance_request of this OptimizedCycle.
        :rtype: bool
        """
        return self._acceptance_request

    @acceptance_request.setter
    def acceptance_request(self, acceptance_request: bool):
        """Sets the acceptance_request of this OptimizedCycle.


        :param acceptance_request: The acceptance_request of this OptimizedCycle.
        :type acceptance_request: bool
        """

        self._acceptance_request = acceptance_request
