from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from energy_manager_service.models.base_model import Model
from energy_manager_service import util


class RecommendationObject(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, recommendation_id=None, serial_number=None, sequence_id=None, accepted=None, optimized_start_time=None, optimized_end_time=None):  # noqa: E501
        """RecommendationObject - a model defined in OpenAPI

        :param recommendation_id: The recommendation_id of this RecommendationObject.  # noqa: E501
        :type recommendation_id: int
        :param serial_number: The serial_number of this RecommendationObject.  # noqa: E501
        :type serial_number: str
        :param sequence_id: The sequence_id of this RecommendationObject.  # noqa: E501
        :type sequence_id: str
        :param accepted: The accepted of this RecommendationObject.  # noqa: E501
        :type accepted: bool
        :param optimized_start_time: The optimized_start_time of this RecommendationObject.  # noqa: E501
        :type optimized_start_time: datetime
        :param optimized_end_time: The optimized_end_time of this RecommendationObject.  # noqa: E501
        :type optimized_end_time: datetime
        """
        self.openapi_types = {
            'recommendation_id': int,
            'serial_number': str,
            'sequence_id': str,
            'accepted': bool,
            'optimized_start_time': datetime,
            'optimized_end_time': datetime
        }

        self.attribute_map = {
            'recommendation_id': 'recommendation_id',
            'serial_number': 'serial_number',
            'sequence_id': 'sequence_id',
            'accepted': 'accepted',
            'optimized_start_time': 'optimized_start_time',
            'optimized_end_time': 'optimized_end_time'
        }

        self._recommendation_id = recommendation_id
        self._serial_number = serial_number
        self._sequence_id = sequence_id
        self._accepted = accepted
        self._optimized_start_time = optimized_start_time
        self._optimized_end_time = optimized_end_time

    @classmethod
    def from_dict(cls, dikt) -> 'RecommendationObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RecommendationObject of this RecommendationObject.  # noqa: E501
        :rtype: RecommendationObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def recommendation_id(self) -> int:
        """Gets the recommendation_id of this RecommendationObject.


        :return: The recommendation_id of this RecommendationObject.
        :rtype: int
        """
        return self._recommendation_id

    @recommendation_id.setter
    def recommendation_id(self, recommendation_id: int):
        """Sets the recommendation_id of this RecommendationObject.


        :param recommendation_id: The recommendation_id of this RecommendationObject.
        :type recommendation_id: int
        """

        self._recommendation_id = recommendation_id

    @property
    def serial_number(self) -> str:
        """Gets the serial_number of this RecommendationObject.


        :return: The serial_number of this RecommendationObject.
        :rtype: str
        """
        return self._serial_number

    @serial_number.setter
    def serial_number(self, serial_number: str):
        """Sets the serial_number of this RecommendationObject.


        :param serial_number: The serial_number of this RecommendationObject.
        :type serial_number: str
        """
        if serial_number is None:
            raise ValueError("Invalid value for `serial_number`, must not be `None`")  # noqa: E501

        self._serial_number = serial_number

    @property
    def sequence_id(self) -> str:
        """Gets the sequence_id of this RecommendationObject.


        :return: The sequence_id of this RecommendationObject.
        :rtype: str
        """
        return self._sequence_id

    @sequence_id.setter
    def sequence_id(self, sequence_id: str):
        """Sets the sequence_id of this RecommendationObject.


        :param sequence_id: The sequence_id of this RecommendationObject.
        :type sequence_id: str
        """
        if sequence_id is None:
            raise ValueError("Invalid value for `sequence_id`, must not be `None`")  # noqa: E501

        self._sequence_id = sequence_id

    @property
    def accepted(self) -> bool:
        """Gets the accepted of this RecommendationObject.


        :return: The accepted of this RecommendationObject.
        :rtype: bool
        """
        return self._accepted

    @accepted.setter
    def accepted(self, accepted: bool):
        """Sets the accepted of this RecommendationObject.


        :param accepted: The accepted of this RecommendationObject.
        :type accepted: bool
        """
        if accepted is None:
            raise ValueError("Invalid value for `accepted`, must not be `None`")  # noqa: E501

        self._accepted = accepted

    @property
    def optimized_start_time(self) -> datetime:
        """Gets the optimized_start_time of this RecommendationObject.


        :return: The optimized_start_time of this RecommendationObject.
        :rtype: datetime
        """
        return self._optimized_start_time

    @optimized_start_time.setter
    def optimized_start_time(self, optimized_start_time: datetime):
        """Sets the optimized_start_time of this RecommendationObject.


        :param optimized_start_time: The optimized_start_time of this RecommendationObject.
        :type optimized_start_time: datetime
        """
        if optimized_start_time is None:
            raise ValueError("Invalid value for `optimized_start_time`, must not be `None`")  # noqa: E501

        self._optimized_start_time = optimized_start_time

    @property
    def optimized_end_time(self) -> datetime:
        """Gets the optimized_end_time of this RecommendationObject.


        :return: The optimized_end_time of this RecommendationObject.
        :rtype: datetime
        """
        return self._optimized_end_time

    @optimized_end_time.setter
    def optimized_end_time(self, optimized_end_time: datetime):
        """Sets the optimized_end_time of this RecommendationObject.


        :param optimized_end_time: The optimized_end_time of this RecommendationObject.
        :type optimized_end_time: datetime
        """
        if optimized_end_time is None:
            raise ValueError("Invalid value for `optimized_end_time`, must not be `None`")  # noqa: E501

        self._optimized_end_time = optimized_end_time
