from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from energy_manager_service.models.base_model import Model
from energy_manager_service import util


class ResponseInfoMessage(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None):  # noqa: E501
        """ResponseInfoMessage - a model defined in OpenAPI

        :param message: The message of this ResponseInfoMessage.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'message': str
        }

        self.attribute_map = {
            'message': 'message'
        }

        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseInfoMessage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseInfoMessage of this ResponseInfoMessage.  # noqa: E501
        :rtype: ResponseInfoMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this ResponseInfoMessage.


        :return: The message of this ResponseInfoMessage.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ResponseInfoMessage.


        :param message: The message of this ResponseInfoMessage.
        :type message: str
        """

        self._message = message
