from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from energy_manager_service.models.base_model import Model
from energy_manager_service import util


class ScheduleResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, serial_number=None, sequence_id=None, schedule=None):  # noqa: E501
        """ScheduleResponse - a model defined in OpenAPI

        :param serial_number: The serial_number of this ScheduleResponse.  # noqa: E501
        :type serial_number: str
        :param sequence_id: The sequence_id of this ScheduleResponse.  # noqa: E501
        :type sequence_id: str
        :param schedule: The schedule of this ScheduleResponse.  # noqa: E501
        :type schedule: List[int]
        """
        self.openapi_types = {
            'serial_number': str,
            'sequence_id': str,
            'schedule': List[int]
        }

        self.attribute_map = {
            'serial_number': 'serial_number',
            'sequence_id': 'sequence_id',
            'schedule': 'schedule'
        }

        self._serial_number = serial_number
        self._sequence_id = sequence_id
        self._schedule = schedule

    @classmethod
    def from_dict(cls, dikt) -> 'ScheduleResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ScheduleResponse of this ScheduleResponse.  # noqa: E501
        :rtype: ScheduleResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def serial_number(self) -> str:
        """Gets the serial_number of this ScheduleResponse.


        :return: The serial_number of this ScheduleResponse.
        :rtype: str
        """
        return self._serial_number

    @serial_number.setter
    def serial_number(self, serial_number: str):
        """Sets the serial_number of this ScheduleResponse.


        :param serial_number: The serial_number of this ScheduleResponse.
        :type serial_number: str
        """

        self._serial_number = serial_number

    @property
    def sequence_id(self) -> str:
        """Gets the sequence_id of this ScheduleResponse.


        :return: The sequence_id of this ScheduleResponse.
        :rtype: str
        """
        return self._sequence_id

    @sequence_id.setter
    def sequence_id(self, sequence_id: str):
        """Sets the sequence_id of this ScheduleResponse.


        :param sequence_id: The sequence_id of this ScheduleResponse.
        :type sequence_id: str
        """

        self._sequence_id = sequence_id

    @property
    def schedule(self) -> List[int]:
        """Gets the schedule of this ScheduleResponse.


        :return: The schedule of this ScheduleResponse.
        :rtype: List[int]
        """
        return self._schedule

    @schedule.setter
    def schedule(self, schedule: List[int]):
        """Sets the schedule of this ScheduleResponse.


        :param schedule: The schedule of this ScheduleResponse.
        :type schedule: List[int]
        """

        self._schedule = schedule
