from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from energy_manager_service.models.base_model import Model
from energy_manager_service.models.power_units import PowerUnits
from energy_manager_service import util

from energy_manager_service.models.power_units import PowerUnits  # noqa: E501

class Scheduling(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, start_time=None, power_value=None, power_units=None):  # noqa: E501
        """Scheduling - a model defined in OpenAPI

        :param start_time: The start_time of this Scheduling.  # noqa: E501
        :type start_time: datetime
        :param power_value: The power_value of this Scheduling.  # noqa: E501
        :type power_value: float
        :param power_units: The power_units of this Scheduling.  # noqa: E501
        :type power_units: PowerUnits
        """
        self.openapi_types = {
            'start_time': datetime,
            'power_value': float,
            'power_units': PowerUnits
        }

        self.attribute_map = {
            'start_time': 'start_time',
            'power_value': 'power_value',
            'power_units': 'power_units'
        }

        self._start_time = start_time
        self._power_value = power_value
        self._power_units = power_units

    @classmethod
    def from_dict(cls, dikt) -> 'Scheduling':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Scheduling of this Scheduling.  # noqa: E501
        :rtype: Scheduling
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start_time(self) -> datetime:
        """Gets the start_time of this Scheduling.


        :return: The start_time of this Scheduling.
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time: datetime):
        """Sets the start_time of this Scheduling.


        :param start_time: The start_time of this Scheduling.
        :type start_time: datetime
        """
        if start_time is None:
            raise ValueError("Invalid value for `start_time`, must not be `None`")  # noqa: E501

        self._start_time = start_time

    @property
    def power_value(self) -> float:
        """Gets the power_value of this Scheduling.


        :return: The power_value of this Scheduling.
        :rtype: float
        """
        return self._power_value

    @power_value.setter
    def power_value(self, power_value: float):
        """Sets the power_value of this Scheduling.


        :param power_value: The power_value of this Scheduling.
        :type power_value: float
        """
        if power_value is None:
            raise ValueError("Invalid value for `power_value`, must not be `None`")  # noqa: E501
        if power_value is not None and power_value < 0:  # noqa: E501
            raise ValueError("Invalid value for `power_value`, must be a value greater than or equal to `0`")  # noqa: E501

        self._power_value = power_value

    @property
    def power_units(self) -> PowerUnits:
        """Gets the power_units of this Scheduling.


        :return: The power_units of this Scheduling.
        :rtype: PowerUnits
        """
        return self._power_units

    @power_units.setter
    def power_units(self, power_units: PowerUnits):
        """Sets the power_units of this Scheduling.


        :param power_units: The power_units of this Scheduling.
        :type power_units: PowerUnits
        """
        if power_units is None:
            raise ValueError("Invalid value for `power_units`, must not be `None`")  # noqa: E501

        self._power_units = power_units
